ofus/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 主页
    url(r'^', include('ofus_blog.urls', namespace='ofus_blog')),
    # 分类
    url(r'^sort/', include('sort.urls', namespace='sort')),
    # 个人主页
    url(r'^personal/', include('personal.urls', namespace='personal')),
    # MarkDown
    url(r'^mdeditor/', include('mdeditor.urls'))

]

ofus_blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index),
    url(r'^index/$', views.index, name='index'),
    # 登录
    url(r'^login/$', views.user_login, name='login'),
    # 注册
    url(r'^register/$', views.register, name='register'),
    # 验证码
    url(r'^code/$', views.code, name='code'),
    # 邮箱
    # url(r'^email/$', views.send_email, name='email'),
    # 注销
    url(r'exit/$', views.exit, name='exit')
]

personal/urls.py
from django.conf.urls import url

from . import views

urlpatterns =[
    # 个人主页
    url(r'^one_people/$', views.one_people, name='one_people'),
    # 邮箱验证
    url(r'^email_verify/$', views.email_verify, name='email_verify'),
    # 个人资料
    url(r'^one_date/$', views.one_date, name='one_date'),
    # 个人头像
    url(r'^one_date_head/$', views.one_date_head, name='one_date_head'),
    # 发表文章
    url(r'^send_article/$', views.send_article, name='send_article'),
    # 管理文章
    url(r'^manage_article/$', views.manage_article, name='manage_article'),
    # 创建分类
    url(r'^create_type/$', views.create_type, name='create_type'),
    # 文章分类
    url(r'article_inquire/$', views.article_inquire, name='article_inquire')
]

personal/models.py
from django.db import models
from ofus_blog.models import Users
# Create your models here.

# MarkDown
from mdeditor.fields import MDTextField


# 文章分类
class article_type(models.Model):
    # 编号
    id = models.AutoField(primary_key=True)
    # 分类名称
    type_title = models.CharField(max_length=20, default='默认文集', verbose_name='分类名称')
    # 创建时间
    create_time = models.DateTimeField(auto_now_add=True)
    # 所属用户id外键
    user_id = models.CharField(max_length=255)


# 文章
class article(models.Model):
    # 编号
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=40, verbose_name='文章标题')
    content = MDTextField(default='')
    publishTime = models.DateTimeField(auto_now_add=True, verbose_name='创建文章的时间')
    modifyTime = models.DateTimeField(auto_now=True, verbose_name='每次修改文章的时间')
    Introduction = models.CharField(max_length=255, null=True, blank=True, verbose_name='文章简介')
    # 外键 关联分类
    article_type = models.ForeignKey(article_type, on_delete=models.CASCADE, verbose_name='分类')

personal/views.py
from django.shortcuts import render
from django.shortcuts import redirect, reverse
# model,QuerySet 序列化成json
from django.core import serializers

from django.http import JsonResponse
# 引入内置models
from django.contrib.auth.models import User
# 引入用户信息
from ofus_blog.models import Users
# 引入工具包
from . import utils
# redis缓存
from django.core.cache import cache
# 用户验证登录方法
from django.contrib.auth.decorators import login_required
# 获取时间
from django.utils import timezone

# MarkDown
import markdown

from . import models

import re


# 获取cookie
def cookie(request):
    v = request.COOKIES.get('user_cookie')
    return v


# 装饰器判断邮箱是否验证
def email_auth(func):
    def inner(request, *args, **kwargs):
        # 获取cookie
        try:
            cook = request.COOKIES.get('user_cookie')
            # 如果不存在cookie
            if cook:
                user = User.objects.get(username=cook)
                users = models.Users.objects.get(user_id=user.id)
                if users.email_verify == '0':
                    # 跳转到邮箱验证页面
                    return redirect(reverse('personal:email_verify'))
        except:
            return redirect(reverse('ofus_blog:login'+'?xuyaologin'))
        return func(request, *args, **kwargs)
    return inner


# 个人主页
@email_auth
def one_people(request):
    cookie_user = cookie(request)
    print('123456432134567543', request.user.id)
    return render(request, 'personal/one_people.html', {'msg': cookie_user})


# 个人资料
@login_required
def one_date(request):
    if request.method == 'GET':
        return render(request, 'personal/one_date.html')

    elif request.method == 'POST':  # 到底用那种方法 get传还是 session - request.user传
        gender = request.POST['gender']
        email = request.POST['email']
        print(gender, email)
        try:
            user = models.User.objects.get(username=request.user.username)
            print(user.email)
            user.email = email
            users = Users.objects.get(user_id=user.id)
            print(users.gender)
            users.gender = gender
            user.save()
            users.save()
            return redirect(reverse('personal:one_date'))
        except:
            return render(request, 'personal/one_date.html', {'msg': '错误'})


# 个人头像
def one_date_head(request):
    # 获得Users用户信息
    users = Users.objects.get(user_id=request.user.id)
    if request.method == 'GET':
        return render(request, 'personal/one_date_head.html', {'users': users})
    elif request.method == 'POST':
        # 修改头像
        head = request.FILES['head']
        print(head)
        img = r'^.*(jpg|png)$'
        if re.search(img, str(head)):
            users.header = head
            users.save()
            return render(request, 'personal/one_date_head.html', {'users': users})

    return render(request, 'personal/one_date_head.html', {'msg': '文件错误'})


# 发表文章页面
def send_article(request):
    # GET请求
    if request.method == 'GET':
        # 如果查询到数据
        try:
            article_type = models.article_type.objects.filter(user_id=request.user.id)
            # print(article_type.type_title)
            if article_type:
                # 默认显示已经存在的
                return render(request, 'personal/send_article.html', {'article_type': article_type})
            else:
                raise Exception("用户点击的分类没有文章数据")
        # 如果查询不到数据
        except:
            return render(request, 'personal/send_article.html')
    # POST请求
    elif request.method == 'POST':
        # 获得文本
        title = request.POST['title']
        content = request.POST['my-editormd-html-code']

        return render(request, 'personal/send_article.html')


# 创建文章分类的时候默认创建一篇文章
def create_type(request):
    # 获取用户输入的类型名称
    create_type = request.POST['create_type']
    # 创建文章分类
    create = models.article_type(user_id=request.user.id, type_title=create_type)
    # 保存
    create.save()
    # 获取当前日期
    date = timezone.now().strftime('%Y-%m-%d')
    # 创建一篇空的默认文章
    create_article = models.article(title=date, article_type_id=create.id)
    # 保存
    create_article.save()
    # 返回Json数据
    return JsonResponse(create_type, safe=False)


# 分类文章查询
def article_inquire(request):
    # 前台传来的文章分类
    inquire_type = request.POST['type']
    type = models.article_type.objects.get(type_title=inquire_type)
    # 把QuerySet转成json
    # ajax_articles = serializers.serialize('json', models.article.objects.filter(article_type=type.id))
    articles = models.article.objects.filter(article_type=type.id)
    # 文章名称存入列表
    articles_list = []
    for a in articles:
        articles_list.append(a.title)
    return JsonResponse(articles_list, safe=False)


# 管理文章
def manage_article(request):
    pass


# 验证邮箱
def email_verify(request):
    # 获取cookie用户名
    cookie_user = cookie(request)
    if request.method == 'GET':
        try:
            # 根据用户名查询用户
            user = User.objects.get(username=cookie_user)
            print('1111111', user)
            # 查询用户额外信息
            # users = Users.objects.get(user_id=user.id)
            print('1111111', user)
            # 发送邮件
            print(user.email, user.username)
            utils.send_email(user.email, user.username)
            return render(request, 'personal/email_verify.html', {'email': user.email, 'msg': cookie_user})
        except Exception as e:
            print(e)
            return render(request, 'personal/email_verify.html')

    elif request.method == 'POST':
        # 获取邮箱验证码
        code = request.POST['code']
        # 获取redis
        email_code = cache.get(cookie_user)
        # 验证
        if code == email_code:
            # 根据用户名查询用户
            user = User.objects.get(username=cookie_user)
            users = Users.objects.get(user_id=user.id)
            # 设置为 1 （绑定邮箱模式）
            users.email_verify = '1'
            users.save()
            return redirect(reverse('ofus_blog:index'))
        else:
            # 根据用户名查询用户
            user = models.User.objects.get(username=cookie_user)
            return render(request, 'personal/email_verify.html', {'email': user.email, 'warning': '验证码填写错误,已重新发送验证码', 'msg':cookie_user})

personal/templates/personal/email_verify.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}

<div class="container" style="height: 500px; padding-top: 100px">
    <form action="" method="post">
        {% csrf_token %}
        <p class="">您的邮箱为:<b>{{email}}</b></p>
        <p class="">已经向您的邮箱发送了验证码</p>
        <p class=""><b>3</b>分钟内有效</p>
        <a href="">重新发送验证码(三分钟后生效)</a>
        <p style="color: red">{{warning}}</p>
        <div class="input-group">
          <span class="input-group-addon" id="basic-addon1">验证</span>
          <input type="text" name="code" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
        </div>
        <br><br>
        <input type="submit" class="btn btn-primary btn-block">
    </form>
</div>
{% endblock %}
</body>
</html>

personal/templates/personal/manage_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

personal/templates/personal/one_date.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block nav %}
{% endblock %}

{% block body %}
<br>
<div class="container">
    <a href="{% url 'personal:one_people' %}">个人中心</a>

<div id="left" class="container col-md-11" style="height: 500px; padding-top: 50px">

    <div class="input-group">
      <span class="input-group-addon" id="basic-addon1">{{request.user.username}}</span>
      <input type="text" class="form-control" placeholder="不可修改" disabled="disabled" aria-describedby="basic-addon1">
    </div>

    <br><br>

    <!--<div class="input-group">-->
      <!--<span class="input-group-addon" id="basic-addon2">密码</span>-->
      <!--<input type="text" name="password" class="form-control" placeholder="Password" aria-describedby="basic-addon1">-->
    <!--</div>-->

    <!--<br><br>-->
    <form method="POST" action="">
        {% csrf_token %}
        {{msg}}
        <div class="input-group">
          <span class="input-group-addon" id="basic-addon3">性别</span>
          <input type="text" name="gender" class="form-control" placeholder="{{request.user.users.gender}}" aria-describedby="basic-addon1">
        </div>

        <br><br>

        <div class="input-group">
          <span class="input-group-addon" id="basic-addon4">邮箱</span>
          <input type="text" name="email" class="form-control" placeholder="{{user.email}}" aria-describedby="basic-addon1">
        </div>

        <br><br>

        <input type="submit" class="btn btn-primary btn-block">
    </form>

</div>
<div class="col-md-1 text-center" style="margin-top: 150px">
    <a id="image" href="javascript:void(0)">
        <img src="{% static 'personal/images/箭头右.png' %}">
    </a>
</div>
</div>
<script>
    $(function () {
        $('#left').animate({'left':'10px'},function () {

    });

        $('#image').click(function () {
            $('#left').animate({'left':'-1500px'},function () {
                window.location.href="{% url 'personal:one_date_head' %}";
            });
        })
    })
</script>

{% endblock %}
</body>
</html>

personal/templates/personal/one_date_head.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block nav %}
{% endblock %}

{% block body %}
<br>
    <div class="container">
    <a href="{% url 'personal:one_people' %}">个人中心</a>
    <div class="col-md-1 text-center" style="margin-top: 150px">
        <a id="image" href="javascript:void(0)">
            <img src="{% static 'personal/images/箭头.png' %}">
        </a>
    </div>

    <div id="left" class="col-md-10 container" style="height: 500px; padding-top: 50px; left: 500px">
        <!--margin-left: 500px-->
        {{msg}}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row text-center">
              <div class="col-sm-6 col-md-12">
                <div class="thumbnail">
                    <a id="aaa" href="javascript:void(0)" >
                        <img id="show" src="/{{users.header}}" style="height: 300px" alt="修改头像">
                    </a>
                    <input id="file" onchange="echo()"  name="head" type="file" style="opacity: 0">
                  <div class="caption">
                    <p><input id="open" type="submit" value="提交" class="btn btn-primary btn-block"></p>
                  </div>
                </div>
              </div>
            </div>
        </form>
    </div>
</div>

<script>
    $(function () {
         $('#left').animate({'left':'10px'},function () {

    });

        $('#image').click(function () {
            $('#left').animate({'left':'800px'},function () {
                window.location.href="{% url 'personal:one_date' %}";
            })

        });

        $('#aaa').click(function () {
            $('#file').click()
        });

    });

    function echo () {
      var r= new FileReader();
      f=document.getElementById('file').files[0];

      r.readAsDataURL(f);
      r.onload=function (e) {
        document.getElementById('show').src=this.result;
      };
        }


</script>
{% endblock %}
</body>
</html>

personal/templates/personal/one_people.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}
    <!--不要的搜索框-->
    {% block search %}
    {% endblock %}
<div class="container text-center">
    <div class="row">
      <div class="col-sm-6 col-md-6">
        <div class="thumbnail">
          <img src="{% static 'personal/images/个人资料.png'  %}" alt="...">
          <div class="caption">
            <h3>个人资料</h3>
            <p>详细个人信息的修改</p>
            <p><a href="{% url 'personal:one_date' %}" class="btn btn-primary" role="button">OPEN</a></p>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-6">
        <div class="thumbnail">
          <img src="{% static 'personal/images/编辑文章.png' %}" alt="...">
          <div class="caption">
            <h3>发表文章</h3>
            <p>写文章</p>
            <p><a href="{% url 'personal:send_article' %}" class="btn btn-primary" role="button">OPEN</a></p>
          </div>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-sm-6 col-md-6">
        <div class="thumbnail">
          <img src="{% static 'personal/images/管理.png' %}" alt="...">
          <div class="caption">
            <h3>管理文章</h3>
            <p>修改与删除</p>
            <p><a href="#" class="btn btn-primary" role="button">OPEN</a></p>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-md-6">
        <div class="thumbnail">
          <img src="{% static 'personal/images/空框.png' %}" alt="...">
          <div class="caption">
            <h3>预留</h3>
            <p>...</p>
            <p><a href="#" class="btn btn-primary" role="button">OPEN</a></p>
          </div>
        </div>
      </div>
    </div>
</div>

{% endblock %}
</body>
</html>

personal/templates/personal/send_article.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block css %}
        <link rel="stylesheet" href='{% static "personal/editor.md/css/editormd.css" %}'>
	    <script src='{% static "personal/editor.md/editormd.min.js" %}'></script>
        <link rel="stylesheet" href="{% static 'personal/css/app/send_article.css' %}">
    {% endblock %}
</head>
<body>
<!--nav-->
{% block nav %}
{% endblock %}

{% block body %}
<div class="container-fluid " style="padding:0;">
    <div class="col-md-2 col-lg-2 left text-center" style="padding:0; overflow-y: auto;">
        <div class="left-top">
            <a href="{% url 'ofus_blog:index' %}">回首页</a>
        </div>
        <div class="left-ul text-left">
            <ul id="ul">
                <li><a id="create" value="新建文集" href="javascript:void(0)">新建文集</a></li>
                <li id="llli">
                    <input id="article-type" name="name" type="text">
                    <button id="article-type-button">提交</button>
                </li>
                {% for type in article_type %}
                <li><a class="click" value="{{type.type_title}}" href="javascript:void(0)">{{type.type_title}}</a></li>
                {% empty %}
                <li><a class="" value="木有" href="javascript:void(0)">木有</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="left-down text-left">
            <a href="">
                设置
            </a>
        </div>
    </div>

    <div class="col-md-2 in" style="padding:0;">

            <div style="height:100vh; overflow-y: scroll;">
                <div class="in-top">
                    <a href="">新建文章</a>
                </div>
                <ul class="in-ul">
                    <!--<li>-->
                        <!--<img src="123">-->

                        <!--<a href=""><span>2018-17-27</span></a>-->
                        <!--<a href=""><img src="124"></a>-->
                    <!--</li>-->
                </ul>
            </div>

    </div>

    <div class="col-md-8" style="padding:0; margin: 0;">
        <form action='' method='POST'>
        {% csrf_token %}
            <!--<input type="submit">-->
            <div class="text-center">
                标题
                <input type="text" name="title" class="title">
                <input type="submit" class="btn btn-default">
            </div>
            <div id="my-editormd" >
                <textarea id="my-editormd-markdown-doc" name="my-editormd-markdown-doc" style="display:none"></textarea>
                 <!--注意：name属性的值-->
                <textarea id="my-editormd-html-code" name="my-editormd-html-code" style="display:none;"></textarea>
                 <!--注意：如果查询到数据-->

                <!--<textarea class="editormd-markdown-textarea" name="test-editormd-markdown-doc" style="display: none;"></textarea>-->
            </div>

        </form>
    </div>
</div>
    <script>
		  $(function() {
				editormd("my-editormd", {//注意1：这里的就是上面的DIV的id属性值
				width   : "100%",
				height  : '89vh',
				syncScrolling : "single",
                watch:  false,
				path    : "{% static 'personal/editor.md/lib/' %}",//注意2：你的路径
                toolbarAutoFixed: false,
				saveHTMLToTextarea : true,//注意3：这个配置，方便post提交表单

				/**上传图片相关配置如下*/
				// imageUpload : true,
				// imageFormats : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
				// imageUploadURL : "",//注意你后端的上传图片服务地址
			  });
		  });

          // 点击新建文集
		  $(function () {

		      $('#llli').hide();
		      // 点击新建文章
		      $('#create').click(function () {
                  $('#llli').slideToggle('show')
              });


		      // 新建分类
		      $('#article-type-button').click(function () {
		          // 获取输入的分类名称
                  var create_type = $('#article-type').val();
                  $.ajax({
                      url:'/personal/create_type/',
                      method: 'POST',
                      data:{'create_type': create_type, 'csrfmiddlewaretoken': '{{csrf_token}}'},
                      dataType: 'json',
                      success: function (date) {
                          console.log(date);
                          $("#ul").append("<li><a class=\"click\" value="+ date +" href=\"javascript:void(0)\">"+date+"</a></li>");
                      }
                  })
              });


		      // 请求点击分类文章中的
		      $('.click').click(function () {
		          // 用户点击的分类名
		          var type = $(this).attr('value');
		          // console.log(type);
                  $.ajax({
                      url:'/personal/article_inquire/',
                      method: 'POST',
                      data: {'type': type, 'csrfmiddlewaretoken': '{{csrf_token}}'},
                      dataType: 'json',
                      success: function (date) {
                          // 先吧显示的文章删除
                          $('.in-ul').empty();
                          // 再添加文章
                          $('.in-ul').append();
                          // console.log(date)
                          // 循环后台传来的列表
                          $.each(date, function (k,v) {
                              // 这是文章标题
                              $(".in-ul").append("" +
                                  "<li>\n" +
                                  "<img src=\"123\">\n" +
                                  "\n" +
                                  "<a href=\"javascript:void(0)\"><span class='article_title'>"+v+"</span></a>\n" +
                                  "<a href=\"\"><img src=\"124\"></a>\n" +
                                  "</li>")
                          });
                            // $('.editormd-markdown-textarea').val("设么贵");
                      }
                  });

              })
          })
    </script>
{% endblock %}

{% block under %}
{% endblock %}
</body>
</html>