ofus/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 主页
    url(r'^', include('ofus_blog.urls', namespace='ofus_blog')),
    # 分类
    url(r'^sort/', include('sort.urls', namespace='sort')),
    # 个人主页
    url(r'^personal/', include('personal.urls', namespace='personal')),
    # MarkDown
    url(r'^mdeditor/', include('mdeditor.urls'))

]

ofus_blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index),
    url(r'^index/$', views.index, name='index'),
    # 登录
    url(r'^login/$', views.user_login, name='login'),
    # 注册
    url(r'^register/$', views.register, name='register'),
    # 验证码
    url(r'^code/$', views.code, name='code'),
    # 邮箱
    # url(r'^email/$', views.send_email, name='email'),
    # 注销
    url(r'exit/$', views.exit, name='exit')
]

personal/urls.py
from django.conf.urls import url

from . import views

urlpatterns =[
    # 个人主页
    url(r'^one_people/$', views.one_people, name='one_people'),
    # 邮箱验证
    url(r'^email_verify/$', views.email_verify, name='email_verify'),
    # 个人资料
    url(r'^one_date/$', views.one_date, name='one_date'),
    # 个人头像
    url(r'^one_date_head/$', views.one_date_head, name='one_date_head'),
    # 发表文章
    url(r'^send_article/$', views.send_article, name='send_article'),
    # 管理文章
    url(r'^manage_article/$', views.manage_article, name='manage_article'),
    # 创建分类
    url(r'^create_type/$', views.create_type, name='create_type'),
    # 文章分类
    url(r'article_inquire/$', views.article_inquire, name='article_inquire')
]

sort/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [

    # it分类
    url(r'^it/$', views.it, name='it'),
    # 绘画
    url(r'^draw/$', views.draw, name='draw'),
    # 想法
    url(r'^idea/$', views.draw, name='idea'),
    # 生活
    url(r'^live/$', views.draw, name='live'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html><!--首页-->
    <head>
        <meta charset="UTF-8">
        <style></style>
        <link rel="stylesheet" href="{% static 'js/lib/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/app/base.css' %}">
        <script src="{% static 'js/lib/jquery2.2.4/jquery-2.2.4.js' %}"></script>
        <script src="{% static 'js/lib/bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
		<!-- css -->
		{% block css %}
		
		{% endblock %}

    </head>

<body>
<div class="bg">
<!------------------------------------------导航------------------------------------------>
{% block nav %}
<nav class="navbar navbar-default navbg">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'ofus_blog:index' %}">OF US</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'ofus_blog:index' %}">首页 <span class="sr-only">(current)</span></a></li>
        <!--<li><a href="#">分类</a></li>-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">分类<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'sort:it' %}">IT</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'sort:draw' %}">绘画</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'sort:idea' %}">想法</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'sort:live' %}">生活</a></li>
          </ul>
        </li>
      </ul>
        {% block search %}
    <!--搜索框-->
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="搜索">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
        {% endblock %}
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">关于</a></li>

        <li class="dropdown">
            {% block login %}
                {% if msg %}
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            {{msg}}
                  <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li role="separator" class="divider"></li>
                    <li><a data-toggle="modal" href="{% url 'personal:one_people' %}">个人中心</a></li>
                      <!--弹出框-->
                    <li><a  data-toggle="modal" href="{% url 'ofus_blog:exit' %}">注销</a></li>
                    <li><a href="#">注意事项</a></li>
                    <li role="separator" class="divider"></li>
                    <!--<li><a href="#">小黑屋</a></li>-->
                  </ul>
                {% else %}
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                门
                      <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu">
                        <li role="separator" class="divider"></li>
                        <li><a data-toggle="modal" href="{% url 'ofus_blog:login' %}">登陆</a></li>
                          <!--弹出框-->
                        <li><a  data-toggle="modal" href="{% url 'ofus_blog:register' %}">注册</a></li>
                        <li><a href="#">注意事项</a></li>
                        <li role="separator" class="divider"></li>
                        <!--<li><a href="#">小黑屋</a></li>-->
                      </ul>
                {% endif %}
            {% endblock %}
        </li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% endblock %}
<!------------------------------------------导航END------------------------------------------>




<!------------------------------------------下面分为左中右------------------------------------------>

{% block body %}
<!------------------------------------------左------------------------------------------>
<div class="container">

<div class="col-md-3 wd">
	{% block left %}

	{% endblock %}
</div>
<!------------------------------------------左END------------------------------------------>


<!------------------------------------------中------------------------------------------>
{% block in %}
<div class="col-md-9">

<div class="panel panel-default yy">
    <div class="panel-body">
  <!-- Nav tabs 可切换的标签-->
  <!--<ul class="nav nav-tabs nav-tab" role="tablist">-->
  <ul class="nav-tab" role="tablist">
    <li role="presentation" class="active">
        <a href="#home" aria-controls="home" role="tab" data-toggle="tab">全部</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">精了</a></li>

    <!--匿名讨论区-->
    <!--<li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">匿名讨论区</a></li>-->
    <!--<li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>-->
  </ul>
    </div>
</div>


  <!-- Tab panes 切换的标签-->
<div class="tab-content">
    <!--全部 文章和说说都有-->
<div role="tabpanel" class="tab-pane active" id="home">
    <div class="panel panel-default yy">
        <div class="panel-body">
            <!--头像-->
            <div class="col-md-1 tab-left">
                <a><img src="./images/1%20(5).jpeg"></a>
            </div>
            <!--内容-->
            <!--1-->
            <div class="col-md-11 tab-right">
                <ul>
                    <li>DiLei</li>
                    <li>2年前</li>
                    <li>
                        <div class="tab-right-center-top">
                            <a>#搜狗翻译宝##有了TA不一样#</a>
                            外文原声动漫听不懂，尴尬剧情理解坑无穷。
                            中国网球公开赛官方指定翻译机——搜狗翻译宝Pro
                            今日震撼上市。神器在手，外语不愁！让生活从此不一样。
                            转发并关注<a>@搜狗AI硬件 @爱动漫</a> ，9月25日抽取1位
                            粉丝送100元现金红包~~
                        </div>
                        <!--响应式图片问题-->
                        <div class="tab-right-center-down">
                            <img class="tab-right-center-down-left" src="./images/sg.jpg">
                            <div class="tab-right-center-down-right">
                                <a>
                                    <h4>搜狗翻译宝</h4>
                                    <span class="text-left">
                                        外文原声动漫听不懂，尴尬剧情理解坑无穷。
                                        中国网球公开赛官方指定翻译机——搜狗翻译宝Pro
                                        今日震撼上市。神器在手，外语不愁！让生活从此不一样。
                                    </span>
                                </a>
                            </div>
                        </div>
                    </li>
                    <li class="tab-right-down">
                        <span><img src="./images/眼睛.png">1.95k</span>
                        <span><img src="./images/信息.png">36</span>
                        <span><img src="./images/赞.png">15</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
<!--2-->
    <div class="panel panel-default yy">
        <div class="panel-body">
            <!--头像-->
            <div class="col-md-1 tab-left">
                <a><img src="./images/1%20(5).jpeg"></a>
            </div>
            <!--内容-->
            <div class="col-md-11 tab-right">
                <ul>
                    <li>DiLei</li>
                    <li>2年前</li>
                    <li>
                        <div class="tab-right-center-top">
                            上海中心大厦是中国第一高楼，世界第二高楼，
                            它不仅有壮丽的外观，其内部更是有内涵，
                            B站up主和2233娘空降上海云中之巅，
                            带您开启中华文化瑰宝之旅~(°∀°)ﾉ
                            #哔哩哔哩# L海上云中，一脉相承---上海中心 ​​​​
                        </div>
                        响应式图片问题
                        <div class="tab-right-center-down">
                            <img class="tab-right-center-down-left" src="./images/sg.jpg">
                            <div class="tab-right-center-down-right">
                                <a>
                                    <h4>搜狗翻译宝</h4>
                                    <span class="text-left">
                                        外文原声动漫听不懂，尴尬剧情理解坑无穷。
                                        中国网球公开赛官方指定翻译机——搜狗翻译宝Pro
                                        今日震撼上市。神器在手，外语不愁！让生活从此不一样。
                                    </span>
                                </a>
                            </div>
                        </div>
                    </li>
                    <li class="tab-right-down">
                        <span><img src="./images/眼睛.png">1.95k</span>
                        <span><img src="./images/信息.png">36</span>
                        <span><img src="./images/赞.png">15</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>


</div>

    <!--精了-->
<div role="tabpanel" class="tab-pane" id="profile">
    <div class="panel panel-default yy">
        <div class="panel-body">
            Basic panel example
        </div>
    </div>
    <div class="panel panel-default yy">
        <div class="panel-body">
            Basic panel example
        </div>
    </div>
</div>

    <!--匿名讨论区-->
<!--<div role="tabpanel" class="tab-pane" id="messages">-->
    <!--<div class="panel panel-default yy">-->
        <!--<div class="panel-body">-->
            <!--Basic panel example-->
        <!--</div>-->
    <!--</div>-->
    <!--<div class="panel panel-default yy">-->
        <!--<div class="panel-body">-->
            <!--Basic panel example-->
        <!--</div>-->
    <!--</div>-->
    <!--<div class="panel panel-default yy">-->
        <!--<div class="panel-body">-->
            <!--Basic panel example-->
        <!--</div>-->
    <!--</div>-->
<!--</div>-->
<!--<div role="tabpanel" class="tab-pane" id="settings">...4</div>-->
</div>

    <!--裙子？-->
    <!--<div class="col-md-12">-->
        <!--<div><images src="./images/footer.png"></div>-->
    <!--</div>-->



</div>
{% endblock %}
<!------------------------------------------中END------------------------------------------>
</div>
<!------------------------------------------下面分为左中右END------------------------------------------>
</div>
{% endblock %}


<!------------------------------------------下部------------------------------------------>
{% block under %}
<div class="container-fluid gg">
    <div class="col-md-12">
        <div class="gg">
        </div>
    </div>
</div>
{% endblock %}
<!------------------------------------------下部END------------------------------------------>

</body>
</html>